"""
Email delivery service.

Converts Markdown newsletter content to styled HTML and delivers it via
the Resend transactional email platform.
"""

from __future__ import annotations

import logging
import os
import re
from typing import Any

import resend
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# CSS injected into every HTML email — optimised for major email clients.
# ---------------------------------------------------------------------------
_EMAIL_CSS = """
body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
                 Helvetica, Arial, sans-serif;
    font-size: 16px;
    line-height: 1.6;
    color: #1a1a1a;
    background-color: #ffffff;
    margin: 0;
    padding: 0;
}
.wrapper {
    max-width: 680px;
    margin: 0 auto;
    padding: 32px 24px;
}
h1 { font-size: 28px; font-weight: 700; color: #111; margin: 0 0 8px; }
h2 { font-size: 22px; font-weight: 600; color: #222; margin: 32px 0 12px; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px; }
h3 { font-size: 18px; font-weight: 600; color: #333; margin: 24px 0 8px; }
p  { margin: 0 0 16px; }
ul, ol { padding-left: 24px; margin: 0 0 16px; }
li { margin-bottom: 6px; }
a  { color: #2563eb; text-decoration: none; }
a:hover { text-decoration: underline; }
blockquote {
    border-left: 4px solid #6366f1;
    margin: 0 0 16px 0;
    padding: 8px 16px;
    background: #f5f3ff;
    color: #4b5563;
    font-style: italic;
}
pre {
    background: #1e1e2e;
    color: #cdd6f4;
    padding: 16px;
    border-radius: 6px;
    overflow-x: auto;
    font-size: 14px;
    line-height: 1.5;
    margin: 0 0 16px;
}
code {
    background: #f3f4f6;
    color: #dc2626;
    padding: 2px 6px;
    border-radius: 4px;
    font-size: 13px;
    font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;
}
pre code {
    background: transparent;
    color: inherit;
    padding: 0;
    border-radius: 0;
    font-size: inherit;
}
hr  { border: none; border-top: 1px solid #e5e7eb; margin: 32px 0; }
strong { font-weight: 600; }
.footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 13px; color: #6b7280; }
"""


# ---------------------------------------------------------------------------
# Markdown → HTML converter
# ---------------------------------------------------------------------------


def markdown_to_html(markdown: str) -> str:
    """Convert a Markdown string to an HTML email with inline CSS.

    This is a self-contained, dependency-free converter that handles the
    Markdown subset generated by Claude (headings, bold, italic, code blocks,
    blockquotes, lists, horizontal rules, links). For production deployments
    consider replacing with `mistune` or `markdown2` for full spec compliance.

    Args:
        markdown: The Markdown content to convert.

    Returns:
        Full HTML document string with embedded CSS.
    """
    html = markdown

    # Escape HTML entities before processing.
    html = html.replace("&", "&amp;")
    html = html.replace("<", "&lt;")
    html = html.replace(">", "&gt;")

    # Fenced code blocks (``` ... ```)
    def replace_code_block(m: re.Match) -> str:
        code = m.group(2).strip()
        lang = m.group(1).strip() if m.group(1) else ""
        lang_attr = f' class="language-{lang}"' if lang else ""
        return f"<pre><code{lang_attr}>{code}</code></pre>"

    html = re.sub(r"```(\w*)\n(.*?)```", replace_code_block, html, flags=re.DOTALL)

    # Inline code (`code`)
    html = re.sub(r"`([^`]+)`", r"<code>\1</code>", html)

    # YAML frontmatter block — strip it.
    html = re.sub(r"^---\n.*?\n---\n\n?", "", html, flags=re.DOTALL)

    # Headings
    for level in range(6, 0, -1):
        pattern = r"^" + "#" * level + r"\s+(.+)$"
        html = re.sub(pattern, rf"<h{level}>\1</h{level}>", html, flags=re.MULTILINE)

    # Bold (**text** or __text__)
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
    html = re.sub(r"__(.+?)__", r"<strong>\1</strong>", html)

    # Italic (*text* or _text_)
    html = re.sub(r"\*([^*\n]+)\*", r"<em>\1</em>", html)
    html = re.sub(r"_([^_\n]+)_", r"<em>\1</em>", html)

    # Blockquotes
    html = re.sub(r"^&gt;\s*(.+)$", r"<blockquote>\1</blockquote>", html, flags=re.MULTILINE)

    # Horizontal rules
    html = re.sub(r"^---+$", r"<hr>", html, flags=re.MULTILINE)
    html = re.sub(r"^\*\*\*+$", r"<hr>", html, flags=re.MULTILINE)

    # Links [text](url)
    html = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', html)

    # Unordered lists (lines starting with - or *)
    def replace_ul(m: re.Match) -> str:
        items = re.findall(r"^[*\-]\s+(.+)$", m.group(0), re.MULTILINE)
        lis = "".join(f"<li>{item.strip()}</li>" for item in items)
        return f"<ul>{lis}</ul>"

    html = re.sub(r"(?:^[*\-]\s+.+\n?)+", replace_ul, html, flags=re.MULTILINE)

    # Ordered lists
    def replace_ol(m: re.Match) -> str:
        items = re.findall(r"^\d+\.\s+(.+)$", m.group(0), re.MULTILINE)
        lis = "".join(f"<li>{item.strip()}</li>" for item in items)
        return f"<ol>{lis}</ol>"

    html = re.sub(r"(?:^\d+\.\s+.+\n?)+", replace_ol, html, flags=re.MULTILINE)

    # Paragraphs — wrap blocks of text not already in an HTML tag.
    def wrap_paragraphs(text: str) -> str:
        lines = text.split("\n")
        output: list[str] = []
        para_lines: list[str] = []

        def flush_para():
            if para_lines:
                para = " ".join(para_lines).strip()
                if para:
                    output.append(f"<p>{para}</p>")
                para_lines.clear()

        for line in lines:
            stripped = line.strip()
            if not stripped:
                flush_para()
            elif re.match(r"^<(h[1-6]|ul|ol|li|pre|blockquote|hr|p)", stripped):
                flush_para()
                output.append(stripped)
            else:
                para_lines.append(stripped)

        flush_para()
        return "\n".join(output)

    html = wrap_paragraphs(html)

    return (
        f'<!DOCTYPE html>\n<html lang="en">\n<head>\n'
        f'<meta charset="UTF-8">\n'
        f'<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        f"<style>{_EMAIL_CSS}</style>\n"
        f"</head>\n<body>\n"
        f'<div class="wrapper">\n{html}\n</div>\n'
        f'<div class="wrapper footer">'
        f"You're receiving this because you subscribed to Stream2Stack. "
        f"</div>\n"
        f"</body>\n</html>"
    )


# ---------------------------------------------------------------------------
# Email delivery
# ---------------------------------------------------------------------------


def send_newsletter(
    to_email: str,
    subject: str,
    markdown_content: str,
) -> dict[str, Any]:
    """Send a newsletter via Resend.

    Args:
        to_email: Recipient email address.
        subject: Email subject line.
        markdown_content: Full newsletter content in Markdown.

    Returns:
        Resend API response dict (contains `id` on success).

    Raises:
        ValueError: If RESEND_API_KEY is not set or inputs are invalid.
        resend.exceptions.ResendError: On API failure.
    """
    api_key = os.getenv("RESEND_API_KEY")
    if not api_key:
        raise ValueError("RESEND_API_KEY environment variable is not set.")

    from_email = os.getenv("RESEND_FROM_EMAIL", "newsletter@contact.stream2stackai.com")

    if not to_email or "@" not in to_email:
        raise ValueError(f"Invalid recipient email: {to_email!r}")

    html_content = markdown_to_html(markdown_content)

    resend.api_key = api_key

    logger.info("Sending newsletter to %s | subject: %r", to_email, subject)

    params: resend.Emails.SendParams = {
        "from": from_email,
        "to": [to_email],
        "subject": subject,
        "html": html_content,
        "text": markdown_content,  # Plain-text fallback
    }

    response = resend.Emails.send(params)
    logger.info("Newsletter sent successfully. Resend ID: %s", response.get("id"))
    return response


def send_usage_digest(
    to_email: str,
    user_id: str,
    period: str,
    summary: dict,
    cost: dict,
) -> dict[str, Any]:
    """Send a monthly usage digest email to a user.

    Args:
        to_email: Recipient address.
        user_id:  User identifier (shown in email for reference).
        period:   Billing period string e.g. "2026-04".
        summary:  Dict from GET /usage/summary (quotas + plan).
        cost:     Dict from GET /usage/cost (by_operation + totals).

    Returns:
        Resend API response dict.
    """
    api_key = os.getenv("RESEND_API_KEY")
    if not api_key:
        raise ValueError("RESEND_API_KEY environment variable is not set.")

    from_email = os.getenv("RESEND_FROM_EMAIL", "newsletter@contact.stream2stackai.com")

    # Format period "2026-04" → "April 2026"
    from datetime import datetime
    try:
        dt = datetime.strptime(period, "%Y-%m")
        period_label = dt.strftime("%B %Y")
    except ValueError:
        period_label = period

    plan = summary.get("plan", "free").title()
    quotas = summary.get("quotas", {})
    totals = cost.get("totals", {})

    def _quota_row(label: str, key: str) -> str:
        q = quotas.get(key, {})
        used  = q.get("used", 0)
        limit = q.get("limit")
        pct   = q.get("pct")
        limit_str = "Unlimited" if limit is None else f"{limit:,}"
        pct_str   = "" if pct is None else f" ({pct:.0f}%)"
        return f"<tr><td style='padding:6px 8px;color:#555'>{label}</td><td style='padding:6px 8px;text-align:right;font-family:monospace'>{used:,} / {limit_str}{pct_str}</td></tr>"

    quota_rows = "\n".join([
        _quota_row("Newsletters generated", "newsletters"),
        _quota_row("Videos ingested",       "videos"),
        _quota_row("Emails sent",           "emails"),
        _quota_row("Web pages scraped",     "scrapes"),
        _quota_row("LLM tokens used",       "llm_tokens"),
    ])

    by_op = cost.get("by_operation", {})
    op_rows = ""
    for op, data in by_op.items():
        op_label = op.replace("_", " ").title()
        op_rows += (
            f"<tr><td style='padding:6px 8px;color:#555'>{op_label}</td>"
            f"<td style='padding:6px 8px;text-align:right;font-family:monospace'>{data.get('call_count',0)}</td>"
            f"<td style='padding:6px 8px;text-align:right;font-family:monospace'>{data.get('total_tokens',0):,}</td>"
            f"<td style='padding:6px 8px;text-align:right;font-family:monospace'>${data.get('cost_usd',0):.4f}</td></tr>"
        )

    grand_cost = totals.get("cost_usd", 0.0)

    html = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<style>
body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;font-size:16px;line-height:1.6;color:#1a1a1a;background:#fff;margin:0;padding:0}}
.wrap{{max-width:620px;margin:0 auto;padding:32px 24px}}
h1{{font-size:26px;font-weight:700;color:#111;margin:0 0 4px}}
h2{{font-size:18px;font-weight:600;color:#222;margin:28px 0 10px;border-bottom:2px solid #e5e7eb;padding-bottom:4px}}
table{{width:100%;border-collapse:collapse;margin:0 0 16px}}
th{{background:#f9fafb;text-align:left;padding:8px;font-size:12px;text-transform:uppercase;letter-spacing:.05em;color:#6b7280;border-bottom:1px solid #e5e7eb}}
th.right{{text-align:right}}
tr:nth-child(even) td{{background:#f9fafb}}
.total-row td{{font-weight:600;border-top:2px solid #e5e7eb;padding:10px 8px}}
.badge{{display:inline-block;background:#6366f1;color:#fff;padding:2px 10px;border-radius:999px;font-size:13px;font-weight:600}}
.footer{{margin-top:40px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:13px;color:#6b7280}}
</style></head>
<body><div class="wrap">
<h1>Your {period_label} Usage Summary</h1>
<p style="color:#6b7280;margin:4px 0 24px">Stream2Stack &nbsp;·&nbsp; Plan: <span class="badge">{plan}</span></p>

<h2>Quota Usage</h2>
<table>
<thead><tr><th>Resource</th><th class="right">Usage</th></tr></thead>
<tbody>
{quota_rows}
</tbody>
</table>

<h2>AI Cost Breakdown</h2>
{'<table><thead><tr><th>Operation</th><th class="right">Calls</th><th class="right">Tokens</th><th class="right">Cost</th></tr></thead><tbody>' + op_rows + f'<tr class="total-row"><td colspan="3">Total</td><td style="text-align:right;font-family:monospace">${grand_cost:.4f}</td></tr></tbody></table>' if op_rows else '<p style="color:#6b7280">No AI usage recorded this period.</p>'}

<p style="font-size:13px;color:#9ca3af">
  Costs are estimates based on published model pricing. Actual charges depend
  on your API provider.
</p>

<div class="footer">
  You're receiving this because you're subscribed to Stream2Stack.<br>
  Manage your preferences at <a href="https://stream2stack.com/settings" style="color:#2563eb">stream2stack.com/settings</a>.
</div>
</div></body></html>"""

    plain = (
        f"Stream2Stack — {period_label} Usage Summary\n"
        f"Plan: {plan}\n\n"
        f"Total AI cost: ${grand_cost:.4f}\n\n"
        f"Manage your preferences at https://stream2stack.com/settings"
    )

    resend.api_key = api_key
    subject = f"Your Stream2Stack usage summary — {period_label}"

    logger.info("Sending usage digest to %s for period %s.", to_email, period)
    params: resend.Emails.SendParams = {
        "from": from_email,
        "to":   [to_email],
        "subject": subject,
        "html": html,
        "text": plain,
    }
    response = resend.Emails.send(params)
    logger.info("Usage digest sent. Resend ID: %s", response.get("id"))
    return response
